# Site settings
title: Hi, I'm Divyam.
description: Divyam Agrawal' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Divyam Agrawal
# user_title: Dr.
user_job_title: Data Scientist
email: diagra[at] uw.edu
# twitter_username: d_haitz
github_username:  agrdivyam99

exclude: ['package.json', 'src' , 'node_modules']
